#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace ArcheryTrickShot.CharacterTesting.Editor
{
    /// <summary>
    /// Compatibility entry point for the old CharacterRigTest workflow.
    ///
    /// The project already has a scalable production character roster, so an
    /// Ember gameplay test must not inject/reflect/swap BowController state.
    /// This command now selects the real Ember roster profile, repairs its
    /// material with the production character shader contract, and opens the
    /// real Level01 production scene.
    /// </summary>
    public static class EmberGameplayTestBuilder
    {
        private const string RosterPath =
            "Assets/ArcheryTrickShot/Resources/Archer3D/ArcherCharacterRoster.asset";

        private const string ProductionScenePath =
            "Assets/ArcheryTrickShot/Scenes/Level01.unity";

        private const string LegacyTestScenePath =
            "Assets/CharacterRigTest/Scenes/EmberGameplayTest.unity";

        private const string LegacyRuntimeProfilePath =
            "Assets/CharacterRigTest/Generated/Ember_ArcherRuntimeProfile.asset";

        private const string LegacyRuntimePrefabPath =
            "Assets/CharacterRigTest/Generated/Ember_RuntimeCharacter.prefab";

        [MenuItem("Tools/Archery Trick Shot/Character Rig Test/Create Ember Gameplay Test")]
        public static void CreateEmberGameplayTest()
        {
            ArcherCharacterRoster roster =
                AssetDatabase.LoadAssetAtPath<ArcherCharacterRoster>(
                    RosterPath);

            if (roster == null)
            {
                EditorUtility.DisplayDialog(
                    "Ember Production Test",
                    "ArcherCharacterRoster.asset was not found. The production character system must be restored first.",
                    "OK");
                return;
            }

            Archer3DRuntimeProfile ember =
                roster.FindProfile("ember");

            if (ember == null)
            {
                EditorUtility.DisplayDialog(
                    "Ember Production Test",
                    "Ember is not registered in the production roster yet.\n\n" +
                    "Select:\nAssets/ArcheryTrickShot/Characters/Ember/Ember_Rigged.fbx\n\n" +
                    "Then run:\nTools > Archery Trick Shot > Characters > Create + Select Hyper-Mixamo Archer From Selected",
                    "OK");
                return;
            }

            // Rebuild the runtime material using the same known-good PBR shader
            // contract as Khaem/Nerissa. This repairs profiles generated by the
            // earlier white-placeholder material workflow too.
            ArcherCharacterEditorTools.TryCreateOrUpdateMaterial(
                ember,
                false);

            if (!roster.SelectCharacter("ember"))
            {
                EditorUtility.DisplayDialog(
                    "Ember Production Test",
                    "Ember exists but could not be selected from the production roster.",
                    "OK");
                return;
            }

            ArcherCharacterRoster.InvalidateRuntimeSelectionCache();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                return;

            SceneAsset productionScene =
                AssetDatabase.LoadAssetAtPath<SceneAsset>(
                    ProductionScenePath);

            if (productionScene == null)
            {
                EditorUtility.DisplayDialog(
                    "Ember Production Test",
                    "Production scene was not found at:\n" + ProductionScenePath,
                    "OK");
                return;
            }

            EditorSceneManager.OpenScene(
                ProductionScenePath,
                OpenSceneMode.Single);

            // Remove only obsolete Ember test artifacts. Keep CharacterRigTest
            // itself because it is still useful for validating future Humanoid rigs.
            DeleteLegacyAssetIfPresent(LegacyTestScenePath);
            DeleteLegacyAssetIfPresent(LegacyRuntimeProfilePath);
            DeleteLegacyAssetIfPresent(LegacyRuntimePrefabPath);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Selection.activeObject = ember;
            EditorGUIUtility.PingObject(ember);

            Debug.Log(
                "[Ember Production Test] Ember selected through ArcherCharacterRoster. " +
                "Opened production Level01. No test adapter/profile swap is active.");

            EditorUtility.DisplayDialog(
                "Ember Production Test Ready",
                "Ember is selected through the REAL production roster.\n\n" +
                "Opened:\n" + ProductionScenePath + "\n\n" +
                "No CharacterRigTest runtime adapter, reflection-based profile swap, " +
                "duplicate test archer, or test overlay is used.\n\n" +
                "Press Play and test from the normal menu/campaign flow.",
                "OK");
        }

        [MenuItem("Tools/Archery Trick Shot/Character Rig Test/Open Ember Gameplay Test")]
        public static void OpenEmberGameplayTest()
        {
            // Kept for muscle memory: the old menu now routes to the safe
            // production test instead of reopening a stale duplicated scene.
            CreateEmberGameplayTest();
        }

        private static void DeleteLegacyAssetIfPresent(string path)
        {
            if (AssetDatabase.LoadMainAssetAtPath(path) != null)
                AssetDatabase.DeleteAsset(path);
        }
    }
}
#endif
